Install-Package GoogleChrome -Provider Chocolatey
Install-Package Firefox -Provider Chocolatey
Install-Package vim -Provider chocolatey
Install-Package putty -Provider chocolatey
Install-Package git -Provider chocolatey
#Install-Package dropbox -Provider Chocolatey
Install-Package thunderbird -Provider Chocolatey
Install-Package sumatrapdf -Provider Chocolatey
Install-Package winscp -Provider chocolatey
Install-Package filezilla -Provider Chocolatey
#Install-Package owncloud-client -Provider Chocolatey
#Install-Package GoogleJapaneseInput -Provider chocolatey
Install-Package 7zip -Provider chocolatey
#Install-Package VirtualBox -Provide chocolatey
#Install-Package Vagrant -Provide chocolatey
